---
version: "3"

includes:
  mkdocs: .taskfiles/mkdocs.yml

tasks:
  default:
    cmds:
      - task --list

  init:
    desc: Init project
    silent: true
    cmds:
      - poetry install

  clean:
    desc: Cleanup project
    silent: true
    cmds:
      - poetry env remove --all

  reinit:
    desc: Reinit project
    silent: true
    cmds:
      - task: clean
      - task: init
