---
version: "3"

vars:
  TASK_VERSION: 3.40.0

includes:
  mkdocs: .taskfiles/mkdocs.yml
  update: .taskfiles/update.yml

tasks:
  default:
    cmds:
      - task: help

  bootstrap:
    desc: Bootstrap project
    silent: true
    cmds:
      - poetry install

  clean:
    desc: Cleanup project
    silent: true
    cmds:
      - poetry env remove --all

  reinit:
    desc: Reinit project
    silent: true
    cmds:
      - task: clean
      - task: bootstrap

  help:
    desc: Display help
    silent: true
    cmds:
      - task --list
